services:
  face_landmark_python:
    container_name: face_landmark_python
    image: face_landmark_python
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "3001:3000"
    volumes:
      - ./service.py:/app/service.py
      - ./requirements.txt:/app/requirements.txt
    environment:
      - BENTOML_CONFIG_OPTIONS=api_server.http.port=3000
    restart: unless-stopped

  face_landmark_react:
    container_name: face_landmark_react
    image: face_landmark_react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - face_landmark_python
    restart: unless-stopped 