version: '3'
services:
  face_landmark_model:
    image: face-landmark-model:latest
    build:
      context: ./face_landmark_model
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: bentoml serve service:FaceLandmarkService --development
    volumes:
      - ./face_landmark_model:/app
    environment:
      - BENTOML_CONFIG_OPTIONS=api_server.http.port=3000

  face_landmark_backend:
    image: face-landmark-backend:latest
    build:
      context: ./face_landmark_backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./res:/res
    environment:
      - MODEL_SERVER_URL=http://face_landmark_model:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - face_landmark_model

  face_landmark_frontend:
    image: face-landmark-frontend:latest
    build:
      context: ./face_landmark_frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./res:/app/public/res
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      - face_landmark_backend 