version: '3.8'

services:
  backend:
    image: face-landmark-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./res:/app/res
    environment:
      - PYTHONUNBUFFERED=1
    command: bentoml serve service.py:FaceLandmarkService --port 3000 --reload

  frontend:
    image: face-landmark-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend 